### ISSUE TITLE
Running Geobucket on Android 2.3.4

### ISSUE THREAD

**Issue by batje** [davidebukali/geobucket#4]
On a Samsung Galaxy with Android 2.3.4 the GPS keeps on initializing without ever connecting to the GPS. 

The GPS does work in other applications.

This might be caused by the current Geobucket version being compiled against Android 1.5

**Comment by davidebukali** [comment]
The device GPS is checked to be turned on when the GeoBucket app starts and an alert is shown if the GPS is off;  the Start Button is used to start the GPS and also saving of points when the optimum GPS accuracy is achieved. The app will be recompiled with android 3.2 to enable compatibility with 2.3.4.
